name: npm_registry_manage
description: A Flutter application for managing Verdaccio NPM registry
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.2+1
  intl: ^0.19.0
  url_launcher: ^6.2.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
