name: npm_registry_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.1.2
  html: ^0.15.4
  intl: ^0.19.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  crypto: ^3.0.6
  encrypt: ^5.0.1
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.4+3
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/npm.svg
    - assets/images/yarn.svg
    - assets/images/pnpm.svg
    - assets/images/git.svg
    - assets/icons/verdaccio.svg
