name: npm_registry_manager
description: A tool for managing NPM registry packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  crypto: ^3.0.3
  path: ^1.8.3
  equatable: ^2.0.5
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
