name: npm_registry_manager
description: A tool for managing NPM registry packages.
publish_to: 'none'
version: 0.1.0-beta.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  crypto: ^3.0.3
  path: ^1.8.3
  equatable: ^2.0.5
  encrypt: ^5.0.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.9
  archive: ^4.0.1
  flutter_markdown: ^0.7.4+3
  google_fonts: ^6.2.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/npm.svg
    - assets/images/yarn.svg
    - assets/images/pnpm.svg
    - assets/images/git.svg
