name: Daily Commit

on:
  schedule:
    - cron: '50 20 * * *' # 每天下午20点50分（UTC时间）运行
  workflow_dispatch: # 允许手动触发

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create Diary directory if it doesn't exist
        run: |
          mkdir -p Diary
      - name: Add a new file to Diary folder
        run: |
          echo "Today is $(date)" > Diary/daily-$(date +\%Y-\%m-\%d).txt
      - name: Commit and push
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name 'Tianyuyuyuyuyuyu'
          git config --global user.email '1933615755@qq.com'
          git add .
          git commit -m "Daily automated commit for $(date +\%Y-\%m-\%d)"
          # 使用正确的 HTTPS URL 格式，确保不会暴露 token
          git push https://Tianyuyuyuyuyuyu:${ACCESS_TOKEN}@github.com/Tianyuyuyuyuyuyu/TByd.git HEAD:master

